RanvierMUD/ranviermud

package.json
=> Add repository to the package info

ranvier
Specific error info in case of EADDRINUSE or EACCES.
=> Deal with errors while trying to start the server

bundles/core-commands/commands/commands.js
Before:
commands
Commands
===============================================
commands            channels            drop
get                 help                inventory
look                quit                save
who
Channels
===============================================
chat                say                 tell
yell                [ 100/100 hp -- 200/200 energy ]
Now:
c
Commands
===============================================
commands            channels            drop
get                 help                inventory
look                quit                save
who
Channels
===============================================
chat                say                 tell
yell
[ 100/100 hp -- 200/200 energy ]
=> commands: always end with a line break

src/BundleManager.js
Fixes runtime error:
Error: ENOENT: no such file or directory, scandir 'ranviermud/src/../bundles/core-areas/behaviors/item/'
Ref.: #79
=> Do not assume that all types have behaviors

.gitignore, README.mkd, bundles/core-input-events/input-events/login.js, package.json, ranvier, src/Account.js, src/AccountManager.js, src/Player.js, src/WebInterface.js
Addresses parts of #94 
Make a GET request against `hostname:9000/api/[whatever]` to get information.
Right now, you can whitelist by IP address in ranvier.json if you so desire. More authentication is to be added later.
=> Basic api impl

bundles/core-classes/classes/warrior.js, bundles/core-classes/skills/secondwind.js, ranvier, src/RandomUtil.js, src/SkillFlag.js, src/SkillType.js
I hope these comments will be useful for some. 
The server exec needed some cleanup due to remnants from ye olde server, and the I added comments to the Skill-related files to answer questions that I had to ask.
Also, thought it may be best for now to put a link to the `RandomUtil` documentation rather than putting doc-blocks for methods that are encapsulated in a node module.
=> Add comments server and skillflags types

src/Helpfile.js
Implemented usage help for channels, reused some of the templating logic in functions, used String.repeat instead of an array, added a handful of comments.
=> Helpfile refactor, channel usage impl & commenting

bundles/core-classes/classes/mage.js, bundles/core-classes/commands/cast.js, src/Skill.js
Added the mage class so that fireball can actually be used, and to learn how.
=> Add mage & minor refactors to Skill.js

bundles/core-areas/areas/limbo/items.yml, bundles/core-commands/commands/put.js, bundles/core-commands/help/put.yml
Learning how bundles and commands work, added put <item> <container>.
Added custom attribute to item: maxItems.
Unsure if I need to create any listeners for the emitted events at the end?
=> Learning commands: added put <item> <container>

bundles/core-input-events/input-events/confirm-new-password.js, bundles/core-input-events/input-events/new-account-password.js, bundles/core-input-events/input-events/password.js
As someone with sausage fingers who tends to fumble their password typing every now and then, I would appreciate this feature, as may others.
=> Users should have to confirm passwords on account creation

bundles/ranvier-commands/commands/config.js, bundles/ranvier-commands/commands/look.js, bundles/ranvier-commands/help/config.yml, src/Data.js, src/Player.js
Player preferences for #121 
Current options: brief and autoloot. autoloot to be used with loot tables once it's complete (or is it already complete?).
Brief simply displays the room title instead of the whole description.
=> New command: config for #121

bundles/ranvier-commands/commands/look.js, src/Broadcast.js
This is why I should stop coding after 11pm. Playing with some formatting and added a directional map.
=> Playing with some formatting and printing a directions map

src/Character.js
Now we wait until making sure the equip slot is open before removing the item.
=> Fix bug with wear/wield

bundles/debug-commands/commands/teleport.js, ranvier.json
This will demonstrate the ability to teleport to either an online player or a room id. The command works like this:
```
teleport <room/player>
ALIAS: tp
```
=> Add teleport command to debug-commands bundle

bundles/ranvier-commands/commands/quit.js
I fixed my git history, by the way. :neckbeard:
=> Return out of command to disallow quitting during a fight.

bundles/ranvier-input-events/input-events/done.js, src/Area.js, src/Player.js, src/Room.js
Seemed like the player code knew a bit too much about what was in the rooms, so now the room handles event proxying.
=> Proxy room events

docs/_mkdocs/theme/ranvier/base.html, docs/_mkdocs/theme/ranvier/partials/footer.html, docs/extending/areas/scripting.md, docs/extending/bundles.md, docs/extending/classes.md, docs/extending/effects.md, mkdocs.yml, package-lock.json
This fixes some broken links in the documentation. All varnings generated by mkdocs have been fixed too, mainly by replacing old, deprecated constructs with new ones.
=> Documentation fixes

src/BundleManager.js
Also, favor const over let/var unless necessary.
=> Add clearer error message if starting room is invalid. 

bundles/ranvier-commands/commands/waypoint.js, bundles/ranvier-effects/effects/regen.js, data/player/Admin.json, src/BundleManager.js, src/Data.js, src/Player.js, src/Room.js, src/Telnet.js, src/Validators.js
For readability and best practices.
=> Use for/of rather than combining for/in with a hasOwnProperties check.

README.mkd
Added your extra 'L' to controlled.
=> Fixed Typo in README.mkd

bundles/ranvier-commands/commands/who.js
=> Who command, by default, shows role now.

bundles/ranvier-input-events/input-events/choose-character.js, package-lock.json
Introduce an async delay so that events happen and the player is consistently booted.
Fixes #206
=> Fix Multiplay Bug

bundles/ranvier-commands/commands/help.js, bundles/ranvier-crafting/commands/craft.js, bundles/ranvier-crafting/help/craft.yml
Also did some refactoring along the way with the help command and rendering of helpfiles/error handling.
=> Fix craft helpfile

bundles/ranvier-classes/player-events.js, bundles/ranvier-classes/skills/shieldblock.js, bundles/ranvier-combat/lib/CombatErrors.js, bundles/ranvier-commands/commands/open.js, bundles/ranvier-npc-behaviors/behaviors/npc/ranvier-sentient.js, gulpfile.js
fix gulp.js, remove obsolete linting paths and add new ones, fix some bugs, mainly visible only in edge cases and involving using undefined variables, mostly caught thanks to the linter
=> linting related fixes

bundles/ranvier-crafting/commands/craft.js, bundles/ranvier-input-events/input-events/choose-character.js
Just some technical debt that was bothering me, and a small thing the linter caught (lol typo woops).
=> Refactor redundant boot function, fix bug in crafting

bundles/ranvier-channels/channels.js, docs/extending/channels.md, src/Channel.js, src/ChannelManager.js
Adding aliases to channels. Added in '.' as alias to the chat as example in the bundle.
=> Added aliases to channels - and to the bundle as example

bundles/ranvier-commands/commands/use.js
Fix use when using before cooldown
=> Fix use when using before cooldown

bundles/ranvier-input-events/input-events/choose-character.js, bundles/ranvier-input-events/input-events/delete-character.js, bundles/ranvier-input-events/input-events/login.js, data/account/Admin.json, src/Account.js
Added delete char and account functionality and metadata to Account
=> Delete char and account functionality

bundles/ranvier-input-events/input-events/choose-character.js
As pointed by @vehn, its a string, not an object - tested and the fix works great.
=> Fix for handleMultiplaying

docs/get_started.md
Updated verbiage based on my question in Slack. Trying out a PR. 😀
=> Changed verbiage in "Testing your changes" instructions.

bundles/ranvier-combat/lib/Combat.js, ranvier, src/Character.js, src/Data.js, src/MobManager.js, src/Npc.js, src/Room.js
Added MobManager and some little validations and fixes
=> MobManager

src/Channel.js
=> Use typeof check so that minRole can be 0.

src/Room.js
=> Add spawn event.

package.json, ranvier
=> Use semver to check for compatible Node version. Use package.json engines prop too.

bundles/ranvier-commands/commands/commands.js
=> `commands` list sorted alphabetically

bundles/ranvier-input-events/input-events/change-password.js, bundles/ranvier-input-events/input-events/delete-character.js
=> Fix copy/paste artifact
